### ISSUE TITLE
Style Guide and Coding Standards Research

### ISSUE THREAD

**Issue by vsinghkpcc** [ProjectLoudly/planning#10]
AC
- [x] Pick a JS framework
- [x] Pick a JS flavor
- [x] Decide on JS coding standard
- [x] Pick a linter
- [x] Pick a Ruby version
- [x] Pick a Rails version
- [x] Pick a Ruby style guide
- [x] Research other technologies / open source projects for new ideas

**Comment by nakedsushi** [comment]
**JS Flavor: ES2015 (formerly known as ES6)**

The decision was between TypeScript vs. ES2015. My votes fare for ES2015 since 1.) I know it better and 2.) there's less visual clutter.

While it's nice that TypeScript is static typed, I don't think the benefits of static typed javascript outweighs the cost: more stuff to type, more stuff to read.

**Comment by sdillingham** [comment]
I think ES2015 is a smart choice. 👍

**Comment by nakedsushi** [comment]
**JS Framework: Angular 2.0**

After doing some due diligence about React, I feel better about picking Angular 2.  The true component-style of Angular 2.0 kills any qualm I have about Angular being too pushy about doing a SPA.

I thought React would be lighter or easier to set up for testing, but I already got decision fatigue going through all of the testing options (Enzyme? Jest?) when setting up my test app.

In the end, all the decisions I have to make with React don't justify any of the benefits I see from it and I'm probably just suffering from FOMO because all the cool kids use React ;)

**Comment by sdillingham** [comment]
@nakedsushi Sounds like you've arrived at a decision that is best for the project. Like we've discussed, both React and Angular are great tools with strong futures, so in the end it's about choosing a framework that you'll feel most productive using.

**Comment by nakedsushi** [comment]
**JS Style Guides**

For vanilla javascript I like https://github.com/rwaldron/idiomatic.js/ since it has a lot of good suggestions and is not too militant about styles.  It's a good guide to writing _thoughtful_ JS.

For ES2015 let's use https://github.com/airbnb/javascript because it has a eslint plugin already and is pretty reasonable but provides guidance on ambiguous things.

**Comment by nakedsushi** [comment]
**Ruby Style Guide**

Is this even a question? The most comprehensive and easy to follow ruby style guide:
https://github.com/bbatsov/ruby-style-guide

And its companion Rails guide: https://github.com/bbatsov/rails-style-guide

**Comment by nakedsushi** [comment]
**Ruby & Rails Version**
Rails 5.0 & Ruby 2.3

Since we're building a completely new set of apps, I see no reason _not_ to go with Rails 5.  rails-api is integrated, `rake` is now integrated to the `rails` command, ActionCable gives us real-time features like sockets. It's always such a pain to upgrade an app from a previous Rails version to the next major version that I'd like to just start off with the newest stable.

And if we're going ahead with Rails 5, then let's just do ruby 2.3 as well (even though Rails 5's minimum requirement is ruby 2.2).  2.3 has the security fixes of 2.2 plus a few extras like the safe navigator operator for people who are tired of typing `if user && user.profile && user.profile.name...` (https://bugs.ruby-lang.org/issues/11537)

**Comment by sdillingham** [comment]
Agreed. Definitely want to use current version of Rails + Ruby, and keep things current as the project progresses.

**Comment by nakedsushi** [comment]
**JS Linter: ESLint**

Easy installation, AirBnB styleguide plugin, easy to change rules. Good stdout of what rules were broken.
