### ISSUE TITLE
Delivery Pipeline Research

### ISSUE THREAD

**Issue by vsinghkpcc** [ProjectLoudly/planning#11]
AC
- [x] Research testing frameworks
- [x] Pick a CI technology
- [x] Pick a "code climate" service
- [ ] ~~Research build technologies to pose to the working group (might be blocked / need to change depending on stakeholder feedback)~~

**Comment by nakedsushi** [comment]
**JS Testing: Protractor, Karma + Jasmine**
Since we'll most likely be using AngularJS for anything user-facing, Protractor for our end-to-end tests and Karma + Jasmine for our unit tests would be the most straight forward.

**Rails Testing: Rspec**
If things go as planned, we'll only be using rails-api, which makes testing really easy. We'll use Rspec to do request testing, which is mainly making sure that any API request returns the correct HTTP response code and the expected response content. (ie: http://matthewlehner.net/rails-api-testing-guidelines/)

**Comment by sdillingham** [comment]
🙌

**Comment by nakedsushi** [comment]
**Code Climate Service: codeclimate**
It's free for open source. Supports eslint. Slack integration.  Can run locally on a docker container. Seems to check for more things than Hound.

**Comment by nakedsushi** [comment]
**CI tech: Travis**
We're already using it for some of our repos. Has code climate integration.  Flexible config. Encrypts secret keys for security. Isn't super confusing with tons of options like Jenkins and the dashboard sure looks a lot better.
