### ISSUE TITLE
Large File Web Upload POC

### ISSUE THREAD

**Issue by vsinghkpcc** [ProjectLoudly/planning#12]
AC
- [x] There is an POC for the web based option for uploading large WAV files
- [x] Decide if it's more useful / feasible to transcode before upload, or transcode after upload

**Comment by nakedsushi** [comment]
Breaking this down into smaller components so that I can keep track of what was done:
- [x] configure angular2 gulp tasks
- [x] get flow.js working with angular2
- [x] set up a rails api server for backend
- [x] test an upload. disconnect halfway, reconnect, resume, etc.
- [x] deploy rails api to aws
- [x] test upload server in aws

**Comment by nakedsushi** [comment]
- [x] figure out why uploaded file isn't the same. Checksum different, a 'pop' at the end of the file when listened to.

**Comment by nakedsushi** [comment]
I got the uploading more stable, but there are still some edge cases that does not upload the complete file.  Instead of trying to work through them, wondering if it's feasible to just do a check of input and output file (checksum it) and if it doesn't match, display an error message to try uploading again.

The main cause of the file mismatch is when users disconnect/reconnect from the network without pausing the upload first.
- [x] add ~~md5sum~~ size check and if doesn't match, display error message and suggest to reupload.

**Comment by nakedsushi** [comment]
- [x] compare sound quality with flac.js and ffmpeg's flac encoding
- [ ] ~~use flac.js to encode the uploaded wav to .flac first and THEN upload it thru flow.js~~

**Comment by nakedsushi** [comment]
Ideally, transcoding using flac.js and uploading the flac would be better since the smaller file size = faster upload.  I'm going to create a new card for that POC.
