### ISSUE TITLE
Fix resound-api dependency vulnerability

### ISSUE THREAD

**Issue by nakedsushi** [ProjectLoudly/planning#165]
Bump the vulnerable dependency up to the version the warning is suggesting and see if that gets rid of the vulnerability warning in github.

AC:
- [x] no more dependency vulnerability warning in https://github.com/ProjectResound/resound-api
- [x] resound-api tests still pass
- [x] resound-api runs locally

**Comment by jo-im** [comment]
Fixed the dependency vulnerability warning in resound-api by upgrading the version. Resound-api tests still passes and runs locally. I also added documentation on how to run the server for development. I have also pushed the fix for dependency vulnerability to production.

The commit that made the fix is here:
https://github.com/ProjectResound/resound-api/commit/7e2264e1b74119df4596844b35f1cad6a28538d8
