### ISSUE TITLE
POC audio conversion listening tests and storage requirements

### ISSUE THREAD

**Issue by vsinghkpcc** [ProjectLoudly/planning#4]
AC
- [x] Work with audio producers to run listening tests on outputs from both FLAC and 256k AAC sources to identify qualitative differences
- [x] Create a report of storage requirements for KPCC based on N number of files
- [x] There is documentation for proposed audio format standards

**Comment by sdillingham** [comment]
@nakedsushi @vsinghkpcc: for the third AC around estimating storage requirements for KPCC, I ran some stats on the `audio/` directory on the media server and here's what I found:
- Total file count: 91,041
- Total mp3 file count: 90,514
- Average file size: 9.05mb

Assuming the vast majority of files on our servers are 64k mp3, that gives us an **Average file duration** of **19.3mins**.

**Comment by nakedsushi** [comment]
Based on our sample, if we store
- flac: .0058M/sec
- aac: .032M/sec

Which if we apply that ratio to our total file counts and average file size, and we pretend we have all the wavs and decided to encode them thru Loudly we'd need:
- 6.1TB for flac
- 3.4TB for aac

**Comment by sdillingham** [comment]
Awesome, thanks for those estimates @nakedsushi. Looking at Amazon's pricing for S3, the monthly storage costs estimate for all of KPCC's current digital audio would be:

FLAC: $233.63/mo (~$2800/yr)
AAC: $130.22/mo (~1600/yr)

Keep in mind that's just for storage of source audio; it doesn't take into account the cost of storing output formats, nor does in include request or transfer costs. 

Still, that's pretty reasonable, and considering we produce a lot more audio than many stations, it makes me think that we wouldn't be priced out of choosing to use a lossless codec (FLAC) for storing source audio.

**Comment by nakedsushi** [comment]
From our chat with Kyle Wesloh and the result of our one listening party, I'm ready to vote in favor of FLAC being our source format. My hypothesis that lossless => lossy would sound a lot better than lossy (AAC) => lossy was validated by our tests where FLAC outperformed AAC in all of the instances where we went to a lower bitrate output format.

As far as output format, considering the widespread support of mp3 and the results where most people preferred listening to the 128k mp3 over the he-aac, is it safe to say that our output format should be mp3?  Or can we leave that choice up to producers with a strong recommendation to use mp3?

**Comment by sdillingham** [comment]
I agree that there's a strong body of evidence and consensus quickly emerging around FLAC as the best source format for Loudly to support. Interested to hear @vsinghkpcc's thoughts, but at this point I'd be comfortable putting that forward as a recommendation to our stakeholders.

As for output formats, I agree that 128k mp3 is a good baseline output format, offering decent audio quality, reasonable file sizes and pretty much universal support. However, in the same way that AssetHost outputs multiple image sizes and crops, I think our Loudly backend system will need to be configurable to support multiple output formats. Here's some common use cases KPCC has to support where a particular output format would be advantageous:
- Deliver to podcast clients: 128kmp3
- Deliver to our mobile apps: 48k HE-AAC
- Deliver to NPR One: 48k HE-AAC
- Deliver to our website: since HTML5 audio supports multiple sources, I might start with 48k HE-AAC as the preferred format and then fall back to 128k Mp3 for browsers that don't support AAC

Other stations might have different needs or preferences, so while we can certainly set some recommended defaults and document best practices, I think we will need to let each station configure the backend system to define the output formats that meet their needs.

**Comment by vsinghkpcc** [comment]
I agree - based on everything we've learned, FLAC should be our recommendation to stakeholders.

Also agree with 128k mp3 being the baseline, but that we'll need to offer additional / configurable output formats.

**Comment by nakedsushi** [comment]
Proposed formats doc here: https://github.com/ProjectLoudly/planning/blob/master/proposed_formats.md

**Comment by sdillingham** [comment]
Cool, I think we've met all the AC for this ticket; moving to Review.
