### ISSUE TITLE
Successful Upload & Processing Adds to Explorer

### ISSUE THREAD

**Issue by nakedsushi** [ProjectLoudly/planning#49]
Once a file is successfully uploaded and processed, it should be removed from the Dropzone and added to the top of Explorer.  If it's not a ton of work, maybe a blind-down effect?

AC
- [x] uploaded file is removed from Dropzone and added to the top of the Explorer queue

**Comment by arellaTV** [comment]
Latest approach can be found in this pull request:
https://github.com/ProjectResound/store-upload/pull/3

Note:

- Audio List array is associated with two types of changes instead of one
  - `getAudioList()`: Replaces the entire list
    - This occurs at component mounting and for displaying search results.
  - `appendAudioList()`: Appends the successfully uploaded file to the top of the list
    - This occurs at successful file upload

- Blind down animation uses CSS animations. A boolean, `isAppending`, indicates whether an animation class should be added to an item or not.
  - In order to get this animation to work, I had to convert the table to a collection of divs (material grid columns and rows).
